apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges
  labels:
    app: challenges
spec:
  selector:
    matchLabels:
        app: challenges
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: challenges
    spec:
      containers:
        - name: challenges
          image: 868981377508.dkr.ecr.eu-west-1.amazonaws.com/challenges/ci-cd-pipeline:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
